# 括弧の対応の可視化
[[plugins]]
repo = 'itchyny/vim-parenmatch'
hook_add = '''
"カッコのハイライト標準オフ
let g:loaded_matchparen = 1
""カッコの対応
source $VIMRUNTIME/macros/matchit.vim
'''

# 行頭行末にあるスペースを可視化
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# textobjの拡張
[[plugins]]
repo = 'kana/vim-textobj-user'

# gcでコメントの切り替えができる
[[plugins]]
repo = 'tpope/vim-commentary'

## 様々なアイコンを追加
#[[plugins]]
#repo = 'ryanoasis/vim-devicons'

# S で括弧の追加等ができる
[[plugins]]
repo = 'tpope/vim-surround'

# 括弧の補完
[[plugins]]
repo = 'Raimondi/delimitMate'

# . の強化
[[plugins]]
repo = 'tpope/vim-repeat'

# endの挿入
[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
let g:rainbow_active = 1
'''

# Undotree
[[plugins]]
repo = 'mbbill/undotree'

#[[plugins]]
#repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = 'python'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'vim-scripts/twilight'

[[plugins]]
repo = 'vim/killersheep'

[[plugins]]
repo = 'jacoborus/tender'

[[plugins]]
repo = 'vim-scripts/Lucius'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#enable_ignore_case = 1
'''

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['lightline.vim', 'ale']

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'joshdick/onedark.vim'

