#!/bin/sh
# created by tomokiz
# write filelist to ~/dotfiles/file.list

echo 'Setup started !'
echo 'Making symbolic link(s) ...'
filelist=`cat ~/dotfiles/file.list | sed '/^#/d'`
numfiles=`echo "$filelist" | wc -l`
for i in `seq $numfiles`;  do
  symbolic="~/"`echo "$filelist" | sed -n "$i"p | awk '{print $2}'`
  if [ -e "$symbolic" ];  then
    echo -e "\e[1;31m[Error] File "$symbolic" has already exist"
  else
    echo -n $symbolic
    deref="~/dotfiles/"`echo "$filelist" | sed -n "$i"p | awk '{print $1}'`
    ln -sf $deref $symbolic
    echo " -> $deref"
  fi
done
echo 'Setup finished!'
