#!/bin/bash
if [ $(acpi | grep Charging | wc -l) -eq 1 ];then
    batstatus="↑"
elif [ $(acpi | grep Discharging | wc -l) -eq 1 ];then
    batstatus="↓"
else
    batstatus="-"
fi
echo "$((($(cat /sys/class/power_supply/BATA/energy_now) * 100) / $(cat /sys/class/power_supply/BATA/energy_full)))%${batstatus} "

