#!/bin/bash
Exec=`nslookup github.com | grep 'timed out' | wc -l`
if [ ${Exec} -ne 0 ]; then
    echo "${Exec}[Error] No Internet Connection!"
    exit
fi
git clone --depth 1 https://github.com/vim/vim.git /tmp/vim
defaultDir=$(pwd)
echo "[Info] Enter the dir /tmp/vim"
cd /tmp/vim/src
echo "[Info] Configuring"
make distclean
confop="--enable-multibyte "
confop="${confop}--enable-luainterp "
confop="${confop}--enable-perlinterp "
confop="${confop}--enable-pythoninterp "
confop="${confop}--enable-python3interp "
confop="${confop}--enable-rubyinterp "
confop="${confop}--enable-luainterp "
confop="${confop}--disable-gui"
./configure ${confop}
echo "[Info] Making"
make -j2
echo "[Info] Installing"
sudo make install
echo "[Info] Back to the dir ${defaultDir}"
cd ${defaultDir}
echo "[Info] Finished!"

